# Generated by Django 5.1.7 on 2025-03-14 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('produktnazev', models.CharField(max_length=130)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('znacka', models.CharField(blank=True, max_length=130, null=True)),
                ('kategorie', models.CharField(blank=True, max_length=130, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('hodnoceni', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('kusy', models.IntegerField(blank=True, default=0, null=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
